# Generated by Django 4.2.16 on 2024-09-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vCera_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JobID', models.CharField(max_length=100, unique=True)),
                ('JobTitle', models.CharField(max_length=255)),
                ('PrimarySkills', models.CharField(max_length=255)),
                ('SecondarySkills', models.CharField(blank=True, max_length=255, null=True)),
                ('Location', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
