# Generated by Django 4.2.16 on 2024-09-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vCera_App', '0002_manager_form_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=255)),
                ('gin_number', models.IntegerField()),
                ('current_role', models.CharField(max_length=255)),
                ('previous_role', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('pillar', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('primary_skills', models.CharField(max_length=255)),
                ('secondary_skills', models.CharField(max_length=255)),
                ('certifications', models.CharField(max_length=255)),
                ('project_history', models.TextField()),
                ('key_achievements', models.TextField()),
                ('performance_data', models.TextField()),
                ('manager_feedback', models.TextField()),
                ('target_role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pillar', models.CharField(max_length=255)),
                ('JobID', models.CharField(max_length=100)),
                ('JobTitle', models.CharField(max_length=255)),
                ('PrimarySkills', models.CharField(max_length=255)),
                ('SecondarySkills', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255)),
                ('Experience', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='manager_form',
        ),
    ]
